spring.application.name=task_management

# DATABASE: Có biến trên server thì ăn theo server, không có thì lấy localhost:5432 máy bạn
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/task_management_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123456}

# JPA / Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
app.jwt.secret=${APP_JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
app.jwt.expiration-ms=86400000


cloudinary.cloud-name=bzlkjvxv
cloudinary.api-key=291653863559499
cloudinary.api-secret=CmUKOpkNQy4alF5G-qjhNF8HALo

# FRONTEND URL: Trên server thì nhận link Vercel, dưới máy thì nhận localhost:5173
app.frontend-url=${APP_FRONTEND_URL:https://task-management-frontend-lime-rho.vercel.app}

# CORS ALLOWED ORIGINS: Cấu hình thêm các origins (phân cách bằng dấu phẩy) nếu cần
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:}

