spring.application.name=task_management
spring.datasource.url=jdbc:postgresql://localhost:5432/task_management_db
spring.datasource.username=postgres
spring.datasource.password=123456

# JPA / Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Hibernate dialect for PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# Expiration: 24 hours (86400000 ms)
app.jwt.expiration-ms=86400000

cloudinary.cloud-name=bzlkjvxv
cloudinary.api-key=291653863559499
cloudinary.api-secret=CmUKOpkNQy4alF5G-qjhNF8HALo

app.frontend-url=http://localhost:5173