-- ==============================================================================
-- 1. DROP BẢNG CŨ THEO ĐÚNG THỨ TỰ RÀNG BUỘC (CASCADE)
-- ==============================================================================
DROP TABLE IF EXISTS
    attachments,
    activity_logs,
    comments,
    tasks,
    task_lists,
    projects,
    workspace_members,
    workspaces,
    users,
    notifications,
    comment_mentions,
    project_invitations
    CASCADE;

-- ==============================================================================
-- 2. TẠO KIỂU ENUM
-- ==============================================================================
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'project_visibility') THEN
CREATE TYPE project_visibility AS ENUM ('PRIVATE', 'WORKSPACE', 'PUBLIC');
END IF;
END $$;

-- ==============================================================================
-- 3. TẠO BẢNG (SCHEMA DEFINITION)
-- ==============================================================================

-- 3.1. Users
CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       email VARCHAR(100) NOT NULL UNIQUE,
                       password_hash VARCHAR(255) NOT NULL,
                       full_name VARCHAR(100) NOT NULL,
                       avatar_url VARCHAR(500),
                       created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3.2. Workspaces
CREATE TABLE workspaces (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name VARCHAR(100) NOT NULL,
                            owner_id BIGINT NOT NULL,
                            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                            CONSTRAINT fk_workspace_owner
                                FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 3.3. Workspace Members
CREATE TABLE workspace_members (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   workspace_id BIGINT NOT NULL,
                                   user_id BIGINT NOT NULL,
                                   role VARCHAR(20) NOT NULL DEFAULT 'MEMBER',
                                   joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

                                   CONSTRAINT fk_workspace_member_workspace
                                       FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE,
                                   CONSTRAINT fk_workspace_member_user
                                       FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
                                   CONSTRAINT unique_user_workspace UNIQUE (workspace_id, user_id)
);

-- 3.4. Projects
CREATE TABLE projects (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          workspace_id BIGINT NOT NULL,
                          title VARCHAR(100) NOT NULL,
                          visibility VARCHAR(100) DEFAULT 'WORKSPACE' NOT NULL,
                          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

                          CONSTRAINT fk_project_workspace
                              FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON DELETE CASCADE
);

-- 3.5. Task Lists
CREATE TABLE task_lists (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            project_id BIGINT NOT NULL,
                            title VARCHAR(100) NOT NULL,
                            position DOUBLE PRECISION NOT NULL,

                            CONSTRAINT fk_task_list_project
                                FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);

-- 3.6. Tasks
CREATE TABLE tasks (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       list_id BIGINT NOT NULL,
                       title VARCHAR(255) NOT NULL,
                       description TEXT,
                       position DOUBLE PRECISION NOT NULL,
                       priority VARCHAR(20) DEFAULT 'MEDIUM',
                       due_date DATE NULL,
                       start_date DATE NULL,
                       assignee_id BIGINT NULL,
                       created_by BIGINT NOT NULL,
                       created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                       updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                       completed_at TIMESTAMP NULL,

                       CONSTRAINT fk_task_list
                           FOREIGN KEY (list_id) REFERENCES task_lists(id) ON DELETE CASCADE,
                       CONSTRAINT fk_task_assignee
                           FOREIGN KEY (assignee_id) REFERENCES users(id) ON DELETE SET NULL,
                       CONSTRAINT fk_task_creator
                           FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE
);
-- 3.7. Comments
CREATE TABLE comments (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          task_id BIGINT NOT NULL,
                          user_id BIGINT NOT NULL,
                          content TEXT NOT NULL,
                          created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                          updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

                          CONSTRAINT fk_comment_task
                              FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE,
                          CONSTRAINT fk_comment_user
                              FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 3.8. Notifications
CREATE TABLE notifications (
                               id BIGSERIAL PRIMARY KEY,
                               recipient_id BIGINT NOT NULL,
                               actor_id BIGINT,
                               title VARCHAR(255) NOT NULL,
                               content TEXT,
                               type VARCHAR(30) NOT NULL,
                               target_id BIGINT,
                               is_read BOOLEAN NOT NULL DEFAULT FALSE,
                               created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),

                               CONSTRAINT fk_notifications_recipient
                                   FOREIGN KEY (recipient_id) REFERENCES users(id) ON DELETE CASCADE,
                               CONSTRAINT fk_notifications_actor
                                   FOREIGN KEY (actor_id) REFERENCES users(id) ON DELETE SET NULL
);
CREATE TABLE comment_mentions (
                                  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                  comment_id BIGINT NOT NULL,
                                  user_id BIGINT NOT NULL,
                                  start_index INT NOT NULL,
                                  length INT NOT NULL,

                                  CONSTRAINT fk_comment_mentions_comment
                                      FOREIGN KEY (comment_id)
                                          REFERENCES comments(id)
                                          ON DELETE CASCADE,

                                  CONSTRAINT fk_comment_mentions_user
                                      FOREIGN KEY (user_id)
                                          REFERENCES users(id)
);
-- Index hỗ trợ tìm kiếm nhanh các comment mà 1 user được tag
CREATE INDEX idx_mentions_user_id ON comment_mentions(user_id);
-- 3.9. Activity Logs
CREATE TABLE activity_logs (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               task_id BIGINT NOT NULL,
                               user_id BIGINT NOT NULL,
                               action VARCHAR(100) NOT NULL,
                               old_value TEXT,
                               new_value TEXT,
                               created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

                               CONSTRAINT fk_activity_task
                                   FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE,
                               CONSTRAINT fk_activity_user
                                   FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 3.10. Attachments
CREATE TABLE attachments (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             task_id BIGINT,
                             comment_id BIGINT,
                             uploaded_by BIGINT NOT NULL,
                             file_name VARCHAR(255) NOT NULL,
                             file_url VARCHAR(500) NOT NULL,
                             content_type VARCHAR(100) NOT NULL,
                             file_size BIGINT NOT NULL,
                             created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                             status VARCHAR(255) NOT NULL DEFAULT 'TEMPORARY',
                             CONSTRAINT fk_attachment_task
                                 FOREIGN KEY (task_id) REFERENCES tasks(id) ON DELETE CASCADE,
                             CONSTRAINT fk_attachment_comment
                                 FOREIGN KEY (comment_id) REFERENCES comments(id) ON DELETE CASCADE,
                             CONSTRAINT fk_attachment_user
                                 FOREIGN KEY (uploaded_by) REFERENCES users(id),
                             CONSTRAINT chk_attachment_owner
                                 CHECK (
                                     status = 'TEMPORARY'
                                         OR
                                     (task_id IS NOT NULL AND comment_id IS NULL)
                                         OR
                                     (task_id IS NULL AND comment_id IS NOT NULL)
                                     )
);
-- Share link project
CREATE TABLE project_invitations (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     project_id BIGINT NOT NULL,
                                     created_by BIGINT NOT NULL,
                                     token VARCHAR(64) UNIQUE NOT NULL,
                                     expires_at TIMESTAMP NOT NULL,
                                     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                     is_active BOOLEAN DEFAULT TRUE,
                                     role VARCHAR(20) NOT NULL DEFAULT 'MEMBER',
                                     requires_approval BOOLEAN DEFAULT FALSE,
                                     CONSTRAINT fk_project
                                         FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE
);
CREATE TABLE project_members (
                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                 project_id BIGINT NOT NULL,
                                 user_id BIGINT NOT NULL,
                                 role VARCHAR(20) NOT NULL DEFAULT 'MEMBER', -- OWNER, ADMIN, MEMBER, VIEWER
                                 invitation_id BIGINT,                       -- Lưu link mời mà user đã dùng để vào (có thể NULL nếu là Owner tạo project)
                                 joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                 status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    -- Đảm bảo 1 user không bị trùng lặp trong 1 project
                                 CONSTRAINT uq_project_user UNIQUE (project_id, user_id),

    -- Khóa ngoại
                                 CONSTRAINT fk_pm_project FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE,
                                 CONSTRAINT fk_pm_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
                                 CONSTRAINT fk_pm_invitation FOREIGN KEY (invitation_id) REFERENCES project_invitations(id) ON DELETE SET NULL
);
-- ==============================================================================
-- 4. TẠO INDEXES TỐI ƯU TRUY VẤN
-- ==============================================================================
CREATE INDEX idx_tasks_list_position ON tasks(list_id, position);
CREATE INDEX idx_task_lists_project_position ON task_lists(project_id, position);
CREATE INDEX idx_notifications_recipient_read ON notifications(recipient_id, is_read, created_at DESC);

-- ==============================================================================
-- 5. CHÈN DỮ LIỆU MẪU (INSERT DATA)
-- ==============================================================================

-- 5.1. Users (6 Users bao gồm user_id = 6)
INSERT INTO users (id, email, password_hash, full_name, avatar_url, created_at) VALUES
                                                                                    (1, 'bangnh@gmail.com', '$2a$10$e8R6.y3D.O2X2zM8G9aY0eT.G8x1h5m0Q2X2zM8G9aY0eT.G8x1h5', 'Nguyễn Hữu Bằng', 'https://i.pravatar.cc/150?u=bangnh', '2026-01-10 08:00:00'),
                                                                                    (2, 'nam.tran@company.com', '$2a$10$e8R6.y3D.O2X2zM8G9aY0eT.G8x1h5m0Q2X2zM8G9aY0eT.G8x1h5', 'Trần Văn Nam', 'https://i.pravatar.cc/150?u=namtran', '2026-01-11 09:15:00'),
                                                                                    (3, 'hoa.le@company.com', '$2a$10$e8R6.y3D.O2X2zM8G9aY0eT.G8x1h5m0Q2X2zM8G9aY0eT.G8x1h5', 'Lê Thị Hoa', 'https://i.pravatar.cc/150?u=hoale', '2026-01-12 10:30:00'),
                                                                                    (4, 'minh.pham@company.com', '$2a$10$e8R6.y3D.O2X2zM8G9aY0eT.G8x1h5m0Q2X2zM8G9aY0eT.G8x1h5', 'Phạm Đức Minh', 'https://i.pravatar.cc/150?u=minhpham', '2026-01-15 14:20:00'),
                                                                                    (5, 'anh.vu@company.com', '$2a$10$e8R6.y3D.O2X2zM8G9aY0eT.G8x1h5m0Q2X2zM8G9aY0eT.G8x1h5', 'Vũ Quỳnh Anh', 'https://i.pravatar.cc/150?u=anhvu', '2026-01-20 11:00:00'),
                                                                                    (6, 'b@1', '$2a$10$VNpb.EqDI5jhM3ZBOPI09uj6ZB8xK7MtIYHzk19oKTiTZpPjISoSW', 'Nguyễn Văn B', 'https://i.pravatar.cc/150?u=user6', '2026-01-21 08:00:00');

SELECT setval(pg_get_serial_sequence('users', 'id'), (SELECT MAX(id) FROM users));

-- 5.2. Workspaces
INSERT INTO workspaces (id, name, owner_id, created_at) VALUES
                                                            (1, 'Công ty Công nghệ Alpha', 1, '2026-02-01 08:30:00'),
                                                            (2, 'Dự án Freelance Personal', 1, '2026-02-15 09:00:00');

SELECT setval(pg_get_serial_sequence('workspaces', 'id'), (SELECT MAX(id) FROM workspaces));

-- 5.3. Workspace Members
INSERT INTO workspace_members (id, workspace_id, user_id, role, joined_at) VALUES
                                                                               (1, 1, 1, 'ADMIN', '2026-02-01 08:30:00'),
                                                                               (2, 1, 2, 'MEMBER', '2026-02-02 09:00:00'),
                                                                               (3, 1, 3, 'MEMBER', '2026-02-02 09:30:00'),
                                                                               (4, 1, 4, 'MEMBER', '2026-02-05 10:00:00'),
                                                                               (5, 1, 5, 'MEMBER', '2026-02-10 14:00:00'),
                                                                               (6, 1, 6, 'MEMBER', '2026-02-12 08:00:00'), -- User 6 thuộc Workspace 1
                                                                               (7, 2, 1, 'ADMIN', '2026-02-15 09:00:00'),
                                                                               (8, 2, 2, 'MEMBER', '2026-02-16 10:00:00');

SELECT setval(pg_get_serial_sequence('workspace_members', 'id'), (SELECT MAX(id) FROM workspace_members));

-- 5.4. Projects (Bảng projects)
INSERT INTO projects (id, workspace_id, title, visibility, created_at) VALUES
                                                                           (1, 1, 'Movie Booking App', 'WORKSPACE', '2026-02-15 10:00:00'),
                                                                           (2, 1, 'E-Commerce Platform', 'WORKSPACE', '2026-02-20 11:00:00'),
                                                                           (3, 1, 'Mobile Banking Revamp', 'PRIVATE', '2026-03-01 13:30:00');

SELECT setval(pg_get_serial_sequence('projects', 'id'), (SELECT MAX(id) FROM projects));

-- 5.5. Task Lists
INSERT INTO task_lists (id, project_id, title, position) VALUES
-- Lists thuộc Project 1: Movie Booking App
(1, 1, 'To Do', 65536.0),
(2, 1, 'In Progress', 131072.0),
(3, 1, 'Code Review', 196608.0),
(4, 1, 'Done', 262144.0),

-- Lists thuộc Project 2: E-Commerce Platform
(5, 2, 'Backlog', 65536.0),
(6, 2, 'In Progress', 131072.0),
(7, 2, 'Done', 196608.0);

SELECT setval(pg_get_serial_sequence('task_lists', 'id'), (SELECT MAX(id) FROM task_lists));

-- 5.6. Tasks (Đã căn chỉnh lại số lượng chuẩn xác: 4/10 cho Project 1 và 1/5 cho Project 2)
INSERT INTO tasks (id, list_id, title, description, position, priority, due_date, assignee_id, created_by, created_at, updated_at, completed_at) VALUES

-- === PROJECT 1: MOVIE BOOKING APP (Tổng 10 Tasks | 4 Completed -> Tỉ lệ 40%) ===
-- Completed Tasks (Nằm trong list_id = 4 "Done", completed_at IS NOT NULL)
(1, 4, 'Hoàn thành giao diện Movie List', 'Dựng UI hiển thị Grid danh sách các phim kèm Carousel.', 65536.0, 'HIGH', '2026-07-25 17:00:00', 6, 1, '2026-07-10 08:00:00', '2026-08-01 15:00:00', '2026-08-01 15:00:00'),
(2, 4, 'Hoàn thành Authentication', 'Hoàn thành đăng nhập và JWT.', 131072.0, 'URGENT', '2026-07-22 17:00:00', 6, 1, '2026-07-05 08:00:00', '2026-08-02 16:00:00', '2026-08-02 16:00:00'),
(3, 4, 'Hoàn thành thiết kế API', 'Hoàn thành tài liệu API Swagger.', 196608.0, 'MEDIUM', '2026-06-25 17:00:00', 6, 1, '2026-06-10 08:00:00', '2026-06-25 16:00:00', '2026-06-25 16:00:00'),
(4, 4, 'Thiết kế CSDL quản lý Vé và Rạp chiếu', 'Đã hoàn thành thiết kế ERD.', 262144.0, 'HIGH', '2026-07-25 17:00:00', 1, 1, '2026-07-15 08:00:00', '2026-07-24 17:00:00', '2026-07-24 17:00:00'),

-- In Progress / To Do Tasks (Chưa completed)
(5, 2, 'Implement VNPay Payment API', 'Tích hợp cổng thanh toán VNPay.', 65536.0, 'HIGH', '2026-08-10 23:59:59', 6, 1, '2026-07-20 09:00:00', '2026-07-28 14:00:00', NULL),
(6, 2, 'Thiết kế Seat Holding Logic', 'Sử dụng Redis TTL để giữ ghế.', 131072.0, 'URGENT', '2026-08-07 18:00:00', 6, 2, '2026-07-21 10:00:00', '2026-07-29 08:30:00', NULL),
(7, 2, 'Tối ưu truy vấn lịch chiếu', 'Tối ưu JOIN Movie, Showtime và Cinema.', 196608.0, 'MEDIUM', '2026-08-20 17:00:00', 6, 1, '2026-07-25 11:20:00', '2026-07-25 11:20:00', NULL),
(8, 2, 'Tích hợp Redis Cache', 'Thêm Redis Cache cho hệ thống.', 262144.0, 'HIGH', '2026-08-25 17:00:00', 6, 1, '2026-07-26 09:00:00', '2026-07-29 16:00:00', NULL),
(9, 1, 'Thiết kế Database Movie Booking', 'Thiết kế ERD cho hệ thống đặt vé.', 65536.0, 'HIGH', '2026-08-15 17:00:00', 6, 1, '2026-07-15 08:00:00', '2026-07-15 08:00:00', NULL),
(10, 1, 'Viết Unit Test', 'Viết unit test cho Booking Service.', 131072.0, 'MEDIUM', '2026-08-20 17:00:00', 6, 1, '2026-07-18 08:00:00', '2026-07-18 08:00:00', NULL),

-- === PROJECT 2: E-COMMERCE PLATFORM (Tổng 5 Tasks | 1 Completed -> Tỉ lệ 20%) ===
-- Completed Task (Nằm trong list_id = 7 "Done", completed_at IS NOT NULL)
(11, 7, 'Cấu hình Server Nginx & SSL Certificate', 'Setup Reverse Proxy và SSL.', 65536.0, 'LOW', '2026-07-26 17:00:00', 4, 4, '2026-07-18 10:00:00', '2026-07-26 15:30:00', '2026-07-26 15:30:00'),

-- In Progress / Backlog Tasks
(12, 6, 'Design Landing Page Banner', 'Thiết kế banner bằng Figma.', 65536.0, 'MEDIUM', '2026-08-02 18:00:00', 5, 2, '2026-07-24 09:30:00', '2026-07-27 10:00:00', NULL),
(13, 5, 'Tích hợp OAuth2 Login', 'Cấu hình Spring Security với Google/Facebook.', 65536.0, 'HIGH', '2026-08-10 23:59:59', 4, 2, '2026-07-26 14:00:00', '2026-07-26 14:00:00', NULL),
(14, 6, 'Xây dựng module Giỏ hàng', 'Lưu giỏ hàng tạm thời vào Redis.', 131072.0, 'URGENT', '2026-07-31 12:00:00', 2, 1, '2026-07-23 16:00:00', '2026-07-29 09:00:00', NULL),
(15, 5, 'Viết Unit Test cho Order Service', 'Đạt code coverage tối thiểu 85%.', 131072.0, 'LOW', '2026-08-15 17:00:00', NULL, 1, '2026-07-27 08:00:00', '2026-07-27 08:00:00', NULL);

SELECT setval(pg_get_serial_sequence('tasks', 'id'), (SELECT MAX(id) FROM tasks));

-- 5.7. Comments
INSERT INTO comments (id, task_id, user_id, content, created_at) VALUES
                                                                     (1, 5, 2, 'Bằng ơi, đã xin được Merchant Key thử nghiệm từ bên VNPay chưa nhỉ?', '2026-07-28 10:15:00'),
                                                                     (2, 5, 6, 'Tôi có rồi nhé Nam, đã gửi file config mẫu qua Slack cho ông rồi đấy.', '2026-07-28 10:20:00');

SELECT setval(pg_get_serial_sequence('comments', 'id'), (SELECT MAX(id) FROM comments));

-- 5.8. Activity Logs
INSERT INTO activity_logs (id, task_id, user_id, action, old_value, new_value, created_at) VALUES
                                                                                               (1, 5, 6, 'MOVED', 'To Do', 'In Progress', '2026-07-28 09:00:00'),
                                                                                               (2, 1, 6, 'COMPLETED', 'In Progress', 'Done', '2026-08-01 15:00:00');

SELECT setval(pg_get_serial_sequence('activity_logs', 'id'), (SELECT MAX(id) FROM activity_logs));

-- 5.9. Attachments

SELECT setval(pg_get_serial_sequence('attachments', 'id'), (SELECT MAX(id) FROM attachments));